# Generated by Django 6.0.5 on 2026-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vidyasetu_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_class',
            field=models.CharField(blank=True, choices=[('11th', '11th'), ('12th', '12th')], max_length=10, null=True),
        ),
    ]
